### PR TITLE
Port Lettuce test infrastructure to aloe

### PR DESCRIPTION
**Pull request by sdreher**
1. Update dependencies
2. Refactor the features file layout: create a common directory in `smart_sa/features`, supporting python code goes into `smart_sa/features/steps`. Both the `features` and  `steps` directory need an `__init__.py` file.
3. Housekeeping: Remove all the `using_selenium` bits. These tests always use selenium.
4. Switch to Chrome / Chromedrive in headless mode. Firefox is fine, but I had trouble getting the tests to work there consistently. Plus, it was considerably slower in my local dev env.
5. `aloe` uses the django test database by default. Move away from using a backing sqlite3 database in favor of fixtures. (@todo - switch this out to factories if possible)
6. Housekeeping: Improve the selenium tests with the `wait..until` pattern to reduce non-determinant failures.
7. `aloe` also likes tests to begin with transition words like `then` and `when`, fixed up some tests that started with `threre` that `aloe` really did not like.

### CODE REVIEW

**Comment by nbuonin** [comment]
@sdreher running these tests locally throws: `OperationalError: Problem installing fixtures: no such table: intervention_activity__old` from the `setUpClass` method in three of the tests. Do I need to do anything to configure my local env?

**Comment by nikolas** [comment]
wow, great work!

**Comment by nikolas** [comment]
Yeah, i'm seeing the same failure is @nbuonin. I think I saw the same error when I was attempting to migrate smart_sa to python 3 / django 2.

**Comment by sdreher** [comment]
I'll check in on this with you both today. Note that this keeps the application at Python 2 for the moment... I have another branch with the Python 3 conversion.

**Pull request merged**
